{% set version = '0.2.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ideafilter
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/IDEAFilter_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/IDEAFilter/IDEAFilter_{{ version }}.tar.gz
  sha256: fec224548450ee8b9429df3848256b004e924e3ca6e69048b3e6f29aa72c9932

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    # The libstdc++.dll provided in libstdcxx v15.1.0 build h904f734_2
    # is missing `_ZSt21ios_base_library_initv`.
    # see: conda-forge/ctng-compilers-feedstock#174
    - libstdcxx !=14.3.0,!=15.1.0  # [win]
  host:
    - r-base
    - r-rcolorbrewer
    - r-crayon
    - r-ggplot2
    - r-pillar >=1.5.0
    - r-purrr
    - r-shiny
    - r-shinytime
  run:
    - r-base
    - r-rcolorbrewer
    - r-crayon
    - r-ggplot2
    - r-pillar >=1.5.0
    - r-purrr
    - r-shiny
    - r-shinytime
  run_constrained:
    - libstdcxx !=14.3.0,!=15.1.0           # [win]

test:
  commands:
    - $R -e "library('IDEAFilter')"           # [not win]
    - "\"%R%\" -e \"library('IDEAFilter')\""  # [win]

about:
  home: https://biogen-inc.github.io/IDEAFilter/, https://github.com/Biogen-Inc/IDEAFilter
  license: MIT
  summary: "When added to an existing shiny app, users may subset any developer-chosen R data.frame
    on the fly. That is, users are empowered to slice & dice data by applying multiple
    (order specific) filters using the AND (&) operator between each, and getting real-time
    updates on the number of rows effected/available along the way. Thus, any downstream
    processes that leverage this data source (like tables, plots, or statistical procedures)
    will re-render after new filters are applied. The shiny module\u2019s user interface
    has a 'minimalist' aesthetic so that the focus can be on the data & other visuals.
    In addition to returning a reactive (filtered) data.frame, 'IDEAFilter' as also
    returns 'dplyr' filter statements used to actually slice the data."
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
