{% set name = "cogmoteGO" %}
{% set version = "0.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/Ccccraz/cogmoteGO/releases/download/v{{ version }}/cogmoteGO-linux-amd64-v{{ version }}.tar.gz  # [linux and x86_64]
    sha256: f65e7ebe636d469ad4dc35d53aef7e95869ee9be19758cd36f096ca3f260f42c  # [linux and x86_64]
  - url: https://github.com/Ccccraz/cogmoteGO/releases/download/v{{ version }}/cogmoteGO-linux-arm64-v{{ version }}.tar.gz  # [linux and aarch64]
    sha256: df1cbcabe65293b6333e8014cc41fb2843c280f61bb5f306e090cfd4bc58f24c  # [linux and aarch64]
  - url: https://github.com/Ccccraz/cogmoteGO/releases/download/v{{ version }}/cogmoteGO-windows-amd64-v{{ version }}.zip  # [win and x86_64]
    sha256: 865463bc9f482d3f4eadcd31599c113f09792108a3d9e38595d05e82f275503e  # [win and x86_64]
  - url: https://github.com/Ccccraz/cogmoteGO/releases/download/v{{ version }}/cogmoteGO-darwin-arm64-v{{ version }}.tar.gz  # [osx and arm64]
    sha256: 6e585806c0743d477ce62215e1c569431bda63959ca241ef0187943eb92c8fe6  # [osx and arm64]

build:
  number: 0
  missing_dso_whitelist:
    - /lib64/libc.so.6  # [linux]
    - /opt/homebrew/opt/zeromq/lib/libzmq.5.dylib  # [osx]
  script:
    - mkdir -p $PREFIX/bin  # [linux or osx]
    - cp cogmoteGO* $PREFIX/bin/  # [linux or osx]
    - chmod +x $PREFIX/bin/cogmoteGO  # [linux or osx]

    # Windows specific
    - mkdir %PREFIX%\\bin  # [win]
    - copy cogmoteGO* %PREFIX%\\bin\\  # [win]
    - copy libzmq-mt-4_3_5.dll %PREFIX%\\bin\\  # [win]

requirements:
  host:
    - zeromq  # [linux or osx]
    - vc  # [win]
  run:
    - zeromq  # [linux or osx]
    - vc  # [win]

test:
  commands:
    - cogmoteGO --version

about:
  home: https://github.com/Ccccraz/cogmoteGO
  summary: '"air traffic control" for remote neuroexperiments'
  description: |
    cogmoteGO is the "air traffic control" for remote neuroexperiments: 
    a lightweight Go system coordinating distributed data streams, commands, 
    and full experiment lifecycle management - from deployment to data collection.
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  doc_url: https://cogmotego.apifox.cn/
  dev_url: https://github.com/Ccccraz/cogmoteGO

extra:
  recipe-maintainers:
    - Ccccraz
